language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "lawhvictoria-github"
    token:
      secure: "a6315db08d1a89e4b03f6491c11fc108c1db2ac1"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
